name: Selenium CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: selenium-demo-web-shop
  cancel-in-progress: false

jobs:

  smoke-cross-browser:
    name: Smoke - ${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
          - edge

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Exibir versões do ambiente
        run: |
          java -version
          mvn -version

      - name: Executar Smoke no ${{ matrix.browser }}
        run: >
          mvn clean test
          -Dtest=RunCucumberTest
          -Dbrowser=${{ matrix.browser }}
          -Dheadless=true
          -Dcucumber.filter.tags="@smoke"

      - name: Publicar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke-${{ matrix.browser }}
          path: target/allure-results
          if-no-files-found: warn
          retention-days: 7

      - name: Publicar relatórios do Maven
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-smoke-${{ matrix.browser }}
          path: target/surefire-reports
          if-no-files-found: warn
          retention-days: 7


  regression-web:
    name: Regression - Chrome
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Exibir versões do ambiente
        run: |
          java -version
          mvn -version
          google-chrome --version

      - name: Executar Regression no Chrome
        run: >
          mvn clean test
          -Dtest=RunCucumberTest
          -Dbrowser=chrome
          -Dheadless=true
          -Dcucumber.filter.tags="@regression"

      - name: Publicar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-regression-chrome
          path: target/allure-results
          if-no-files-found: warn
          retention-days: 7

      - name: Publicar relatórios do Maven
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-regression-chrome
          path: target/surefire-reports
          if-no-files-found: warn
          retention-days: 7


  api-tests:
    name: API - RestAssured
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Exibir versões do ambiente
        run: |
          java -version
          mvn -version

      - name: Executar testes de API
        run: >
          mvn clean test
          -Dtest=ProductApiTest

      - name: Publicar resultados do Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: target/allure-results
          if-no-files-found: warn
          retention-days: 7

      - name: Publicar relatórios do Maven
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-api
          path: target/surefire-reports
          if-no-files-found: warn
          retention-days: 7